const DB_KEY='myfinance_v1';
const defaultData={
  pin:null, autoLock:true, lastActive:Date.now(),
  transactions:[], assets:[], goals:[{id:'g1',name:'เงินสำรองฉุกเฉิน',target:300000,current:0}],
  settings:{currency:'THB',hideZeroDebt:true}
};
let data=load(); let page='dashboard'; let txFilter='all'; let unlocked=!data.pin; let modal=null;
const THB=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(n||0));
const num=n=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:0}).format(Number(n||0));
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(DB_KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(data));data.lastActive=Date.now()}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function inCurrentMonth(t){return (t.date||'').slice(0,7)===monthKey()}
function totals(){const m=data.transactions.filter(inCurrentMonth);const income=m.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0);const expense=m.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0);const assetTotal=data.assets.reduce((s,x)=>s+Number(x.value||0),0);const debtTotal=data.assets.filter(x=>x.kind==='debt').reduce((s,x)=>s+Number(x.value||0),0);const netWorth=assetTotal-(debtTotal||0);return {income,expense,cashflow:income-expense,assetTotal,debtTotal,netWorth}}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function iconFor(cat){const m={'อาหาร':'🍜','เดินทาง':'🚗','ครอบครัว':'👨‍👩‍👧','สุขภาพ':'🩺','การศึกษา':'📚','ท่องเที่ยว':'✈️','ภาษี':'🧾','เงินเดือน':'💼','ปันผล':'💹','ดอกเบี้ย':'🏦','รายได้พิเศษ':'✨','ลงทุน':'📈','โอนเงิน':'🔄','อื่น ๆ':'•'};return m[cat]||'•'}
function render(){document.getElementById('app').innerHTML=!unlocked?lockView():appView(); bind()}
function lockView(){const first=!data.pin;return `<div class="lock"><div class="lock-card"><div class="lock-logo">฿</div><h1>MY FINANCE</h1><p>Private Financial Planner<br>ข้อมูลการเงินเก็บเฉพาะในเบราว์เซอร์บนอุปกรณ์นี้</p>${first?`<div class="field"><label>ตั้ง PIN 4–6 หลัก</label><input id="pin1" class="pin" inputmode="numeric" maxlength="6" type="password"></div><div class="field"><label>ยืนยัน PIN</label><input id="pin2" class="pin" inputmode="numeric" maxlength="6" type="password"></div><button class="primary" id="setupPin">เริ่มใช้งาน</button>`:`<div class="field"><label>PIN</label><input id="unlockPin" class="pin" inputmode="numeric" maxlength="6" type="password" autofocus></div><button class="primary" id="unlockBtn">ปลดล็อก</button>`}<div class="notice">หมายเหตุ: PWA ไม่สามารถใช้ Face ID แบบ native โดยไม่พึ่งระบบ credential ของ iOS ได้ รุ่นนี้จึงใช้ PIN + Auto Lock เพื่อคงแนว Local-only/ไม่ใช้ iCloud</div></div></div>`}
function appView(){return `<main class="shell">${page==='dashboard'?dashboard():page==='transactions'?transactions():page==='assets'?assets():page==='plan'?plan():settings()}</main>${bottomNav()}${modal?sheet():''}`}
function header(title='MY FINANCE',sub='Personal Financial Planner'){return `<div class="header"><div class="brand"><h1>${title}</h1><p>${sub}</p></div><button class="month-btn">${new Date().toLocaleDateString('en-US',{month:'short',year:'numeric'})}</button></div>`}
function dashboard(){const t=totals();const prev=0;const pct=prev?((t.netWorth-prev)/prev*100):0;return `${header()}<section class="hero"><div class="label">Net Worth</div><div class="value">${THB(t.netWorth)}</div><div class="delta">${t.netWorth>0?'●':'○'} Current snapshot ${pct?`· ${pct.toFixed(1)}%`:''}</div></section><div class="grid3"><div class="mini income"><div class="t">รายรับ</div><div class="v">${THB(t.income)}</div></div><div class="mini expense"><div class="t">รายจ่าย</div><div class="v">${THB(t.expense)}</div></div><div class="mini cashflow"><div class="t">Cash Flow</div><div class="v">${THB(t.cashflow)}</div></div></div>${cashChart()}${spendingCard()}${healthCard()}${recentTx()}`}
function cashChart(){let vals=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const k=monthKey(d);const inc=data.transactions.filter(x=>x.type==='income'&&x.date?.startsWith(k)).reduce((s,x)=>s+Number(x.amount),0);const exp=data.transactions.filter(x=>x.type==='expense'&&x.date?.startsWith(k)).reduce((s,x)=>s+Number(x.amount),0);vals.push(inc-exp)}const max=Math.max(...vals.map(v=>Math.abs(v)),1);const pts=vals.map((v,i)=>`${8+i*58},${72-(v/max)*48}`).join(' ');return `<section class="section"><div class="section-title"><h2>Monthly Cash Flow</h2><span>6 เดือน</span></div><div class="card chart-wrap"><svg viewBox="0 0 310 130"><defs><linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#6F87A6" stop-opacity=".24"/><stop offset="1" stop-color="#6F87A6" stop-opacity="0"/></linearGradient></defs><g class="chart-grid"><line x1="8" y1="24" x2="298" y2="24"/><line x1="8" y1="72" x2="298" y2="72"/><line x1="8" y1="120" x2="298" y2="120"/></g><polygon class="chart-area" points="${pts} 298,120 8,120"/><polyline class="chart-line" points="${pts}"/></svg></div></section>`}
function spendingCard(){const tx=data.transactions.filter(x=>x.type==='expense'&&inCurrentMonth(x));const sums={};tx.forEach(x=>sums[x.category]=(sums[x.category]||0)+Number(x.amount));const entries=Object.entries(sums).sort((a,b)=>b[1]-a[1]).slice(0,5);const total=entries.reduce((s,x)=>s+x[1],0)||1;const colors=['#6F8F7B','#C98383','#6F87A6','#C8A867','#88769A'];let acc=0;const stops=entries.length?entries.map(([k,v],i)=>{const a=acc;acc+=v/total*100;return `${colors[i]} ${a}% ${acc}%`}).join(','):'#E7E0D4 0 100%';return `<section class="section"><div class="section-title"><h2>Where My Money Goes</h2><span>เดือนนี้</span></div><div class="card donut-row"><div class="donut" style="background:conic-gradient(${stops})"></div><div class="legend">${entries.length?entries.map(([k,v],i)=>`<div class="legend-item"><span><i class="dot" style="background:${colors[i]}"></i>${esc(k)}</span><b>${Math.round(v/total*100)}%</b></div>`).join(''):'<div class="empty">ยังไม่มีรายจ่าย</div>'}</div></div></section>`}
function healthCard(){const t=totals();let score=50;if(t.cashflow>0)score+=20;if(t.income>0&&t.expense/t.income<.7)score+=15;if(t.debtTotal===0)score+=15;score=Math.max(0,Math.min(100,score));const g=data.goals[0]||{target:1,current:0};const gp=Math.min(100,Math.round((g.current/(g.target||1))*100));return `<section class="section"><div class="section-title"><h2>Financial Health</h2><span>สูตรโปร่งใส</span></div><div class="card health"><div class="score" style="--score:${score}"><strong>${score}</strong></div><div class="health-copy"><h3>${score>=80?'Very Good':score>=60?'Good':'Needs Attention'} ${t.debtTotal===0?'· Debt Free ✓':''}</h3><p>ประเมินจาก Cash Flow, สัดส่วนรายจ่าย และภาระหนี้ที่บันทึกไว้</p><div class="bar"><i style="width:${gp}%"></i></div><p style="margin-top:6px">${esc(g.name)} ${gp}%</p></div></div></section>`}
function recentTx(){const tx=[...data.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5);return `<section class="section"><div class="section-title"><h2>Recent Transactions</h2><span id="seeAll">ดูทั้งหมด</span></div><div class="card tx-list">${tx.length?tx.map(txRow).join(''):'<div class="empty">เริ่มบันทึกรายการแรกด้วยปุ่ม +</div>'}</div></section>`}
function txRow(x){const sign=x.type==='income'?'+':x.type==='expense'?'-':'';const cls=x.type==='income'?'pos':x.type==='expense'?'neg':'';return `<div class="tx" data-id="${x.id}"><div class="tx-ico">${iconFor(x.category)}</div><div class="tx-main"><b>${esc(x.category||x.type)}</b><small>${esc(x.account||'')} · ${esc(x.date||'')}</small></div><div class="amt ${cls}">${sign}${THB(x.amount)}</div></div>`}
function transactions(){let tx=[...data.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||''));if(txFilter!=='all')tx=tx.filter(x=>x.type===txFilter);return `${header('Transactions','รายรับ รายจ่าย โอน และลงทุน')}<h2 class="page-title">รายการทั้งหมด</h2><div class="filters"><button class="chip ${txFilter==='all'?'active':''}" data-filter="all">ทั้งหมด</button><button class="chip ${txFilter==='income'?'active':''}" data-filter="income">รายรับ</button><button class="chip ${txFilter==='expense'?'active':''}" data-filter="expense">รายจ่าย</button><button class="chip ${txFilter==='transfer'?'active':''}" data-filter="transfer">โอน</button><button class="chip ${txFilter==='investment'?'active':''}" data-filter="investment">ลงทุน</button></div><div class="card tx-list">${tx.length?tx.map(txRow).join(''):'<div class="empty">ยังไม่มีรายการในหมวดนี้</div>'}</div>`}
function assets(){const kinds=[['cash','เงินสด/ธนาคาร','💵'],['stock','หุ้น/กองทุน','📈'],['gold','ทอง','🪙'],['property','ที่ดิน/อสังหาฯ','🏡'],['vehicle','รถ/ยานพาหนะ','🚙'],['other','ทรัพย์สินอื่น','◆']];return `${header('Assets','ทรัพย์สินและฐานะสุทธิ')}<h2 class="page-title">My Wealth</h2><div class="asset-grid">${kinds.map(([k,n,ic])=>{const v=data.assets.filter(a=>a.kind===k).reduce((s,a)=>s+Number(a.value||0),0);return `<div class="asset-card"><div class="a-label">${ic} ${n}</div><div class="a-value">${THB(v)}</div><div class="a-sub">${data.assets.filter(a=>a.kind===k).length} รายการ</div></div>`}).join('')}</div><section class="section"><div class="section-title"><h2>รายการทรัพย์สิน</h2><span id="addAsset">+ เพิ่ม</span></div><div class="card tx-list">${data.assets.length?data.assets.map(a=>`<div class="tx asset-row" data-id="${a.id}"><div class="tx-ico">◆</div><div class="tx-main"><b>${esc(a.name)}</b><small>${esc(a.kind)}</small></div><div class="amt">${THB(a.value)}</div></div>`).join(''):'<div class="empty">ยังไม่ได้บันทึกทรัพย์สิน</div>'}</div></section>`}
function plan(){const g=data.goals[0]||{name:'เงินสำรองฉุกเฉิน',target:300000,current:0};const p=Math.min(100,Math.round(g.current/(g.target||1)*100));return `${header('Plan','Budget & Goals')}<h2 class="page-title">Financial Goals</h2><div class="card"><div class="label" style="color:var(--muted)">${esc(g.name)}</div><div style="font-size:28px;font-weight:760;margin-top:6px">${THB(g.current)}</div><div style="font-size:12px;color:var(--muted);margin-top:4px">เป้าหมาย ${THB(g.target)} · ${p}%</div><div class="bar"><i style="width:${p}%"></i></div><button class="secondary" id="editGoal">แก้ไขเป้าหมาย</button></div><section class="section"><div class="section-title"><h2>Budget vs Actual</h2><span>เตรียมไว้สำหรับ V1.1</span></div><div class="card"><p style="margin:0;color:var(--muted);font-size:13px;line-height:1.55">โครงข้อมูลรองรับงบประมาณรายหมวดแล้ว รุ่นนี้เน้นให้ระบบบันทึกรายการและฐานะสุทธิใช้งานได้เสถียรก่อน</p></div></section>`}
function settings(){return `${header('More','Privacy, Backup & Settings')}<h2 class="page-title">Settings</h2><div class="settings-list"><div class="setting"><div><b>Auto Lock</b><small>ล็อกเมื่อออกจากแอปเกิน 1 นาที</small></div><input class="toggle" id="autoLock" type="checkbox" ${data.autoLock?'checked':''}></div><div class="setting"><div><b>Backup ข้อมูล</b><small>ดาวน์โหลดไฟล์ JSON เก็บไว้เอง</small></div><button id="exportBtn">Export</button></div><div class="setting"><div><b>Restore ข้อมูล</b><small>นำไฟล์ Backup กลับเข้าแอป</small></div><button id="importBtn">Import</button></div><div class="setting"><div><b>ล็อกทันที</b><small>กลับไปหน้า PIN</small></div><button id="lockNow">Lock</button></div><div class="setting"><div><b>เปลี่ยน PIN</b><small>ตั้งรหัสใหม่สำหรับเครื่องนี้</small></div><button id="changePin">Change</button></div></div><div class="notice">ข้อมูลแอปนี้ไม่ได้ส่งไปยังเซิร์ฟเวอร์ของผู้พัฒนา แต่การล้างข้อมูลเว็บไซต์/Safari อาจทำให้ข้อมูลในเครื่องหาย ควร Export Backup เป็นระยะ</div>`}
function bottomNav(){const items=[['dashboard','⌂','Dashboard'],['transactions','☷','Transactions'],['add','+',''],['assets','◇','Assets'],['plan','◎','Plan']];return `<nav class="bottom">${items.map(([p,i,l])=>p==='add'?`<button class="add" id="quickAdd">+</button>`:`<button class="nav ${page===p?'active':''}" data-page="${p}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`}
function sheet(){if(modal==='tx')return txSheet();if(modal==='asset')return assetSheet();if(modal==='goal')return goalSheet();if(modal==='pin')return pinSheet();return ''}
function txSheet(){return `<div class="sheet-back" id="sheetBack"><div class="sheet"><div class="grab"></div><h3>เพิ่มรายการ</h3><div class="type-grid">${[['income','💚','รายรับ'],['expense','🩷','รายจ่าย'],['transfer','🔄','โอนเงิน'],['investment','📈','ลงทุน']].map(([t,i,n],idx)=>`<button class="type ${idx===1?'sel':''}" data-txtype="${t}"><strong>${i}</strong>${n}</button>`).join('')}</div><form id="txForm"><input type="hidden" id="txType" value="expense"><div class="field"><label>จำนวนเงิน</label><input id="amount" class="amount-input" inputmode="decimal" type="number" min="0" step="0.01" placeholder="0" required></div><div class="row2"><div class="field"><label>หมวด</label><select id="category"><option>อาหาร</option><option>เดินทาง</option><option>ครอบครัว</option><option>สุขภาพ</option><option>การศึกษา</option><option>ท่องเที่ยว</option><option>ภาษี</option><option>เงินเดือน</option><option>รายได้พิเศษ</option><option>ปันผล</option><option>ดอกเบี้ย</option><option>ลงทุน</option><option>อื่น ๆ</option></select></div><div class="field"><label>บัญชี</label><input id="account" placeholder="เช่น KBank / เงินสด"></div></div><div class="field"><label>วันที่</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>หมายเหตุ</label><input id="note" placeholder="ไม่บังคับ"></div><button class="primary">บันทึก</button></form></div></div>`}
function assetSheet(){return `<div class="sheet-back" id="sheetBack"><div class="sheet"><div class="grab"></div><h3>เพิ่มทรัพย์สิน</h3><form id="assetForm"><div class="field"><label>ชื่อ</label><input id="assetName" required placeholder="เช่น บัญชี KBank"></div><div class="field"><label>ประเภท</label><select id="assetKind"><option value="cash">เงินสด/ธนาคาร</option><option value="stock">หุ้น/กองทุน</option><option value="gold">ทอง</option><option value="property">ที่ดิน/อสังหาฯ</option><option value="vehicle">รถ/ยานพาหนะ</option><option value="other">ทรัพย์สินอื่น</option><option value="debt">หนี้สิน</option></select></div><div class="field"><label>มูลค่าปัจจุบัน</label><input id="assetValue" class="amount-input" type="number" inputmode="decimal" min="0" required></div><button class="primary">บันทึก</button></form></div></div>`}
function goalSheet(){const g=data.goals[0];return `<div class="sheet-back" id="sheetBack"><div class="sheet"><div class="grab"></div><h3>แก้ไขเป้าหมาย</h3><form id="goalForm"><div class="field"><label>ชื่อเป้าหมาย</label><input id="goalName" value="${esc(g.name)}"></div><div class="field"><label>เป้าหมาย</label><input id="goalTarget" type="number" value="${g.target}"></div><div class="field"><label>ปัจจุบัน</label><input id="goalCurrent" type="number" value="${g.current}"></div><button class="primary">บันทึก</button></form></div></div>`}
function pinSheet(){return `<div class="sheet-back" id="sheetBack"><div class="sheet"><div class="grab"></div><h3>เปลี่ยน PIN</h3><form id="pinForm"><div class="field"><label>PIN ใหม่ 4–6 หลัก</label><input id="newPin1" class="pin" type="password" inputmode="numeric" maxlength="6"></div><div class="field"><label>ยืนยัน PIN</label><input id="newPin2" class="pin" type="password" inputmode="numeric" maxlength="6"></div><button class="primary">บันทึก PIN</button></form></div></div>`}
function bind(){
  const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
  if(!unlocked){$('#setupPin')?.addEventListener('click',()=>{const a=$('#pin1').value,b=$('#pin2').value;if(!/^\d{4,6}$/.test(a))return alert('PIN ต้องเป็นตัวเลข 4–6 หลัก');if(a!==b)return alert('PIN ไม่ตรงกัน');data.pin=a;save();unlocked=true;render()});const unlock=()=>{if($('#unlockPin').value===data.pin){unlocked=true;data.lastActive=Date.now();render()}else alert('PIN ไม่ถูกต้อง')};$('#unlockBtn')?.addEventListener('click',unlock);$('#unlockPin')?.addEventListener('keydown',e=>e.key==='Enter'&&unlock());return}
  $$('.nav').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render()}));
  $('#quickAdd')?.addEventListener('click',()=>{modal='tx';render()});
  $('#seeAll')?.addEventListener('click',()=>{page='transactions';render()});
  $$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{txFilter=b.dataset.filter;render()}));
  $('#addAsset')?.addEventListener('click',()=>{modal='asset';render()});
  $('#editGoal')?.addEventListener('click',()=>{modal='goal';render()});
  $('#sheetBack')?.addEventListener('click',e=>{if(e.target.id==='sheetBack'){modal=null;render()}});
  $$('[data-txtype]').forEach(b=>b.addEventListener('click',()=>{$$('[data-txtype]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');$('#txType').value=b.dataset.txtype;const c=$('#category');if(b.dataset.txtype==='income')c.value='เงินเดือน';else if(b.dataset.txtype==='investment')c.value='ลงทุน';else if(b.dataset.txtype==='transfer')c.value='อื่น ๆ';else c.value='อาหาร'}));
  $('#txForm')?.addEventListener('submit',e=>{e.preventDefault();data.transactions.push({id:uid(),type:$('#txType').value,amount:Number($('#amount').value),category:$('#category').value,account:$('#account').value.trim(),date:$('#date').value,note:$('#note').value.trim()});save();modal=null;render()});
  $('#assetForm')?.addEventListener('submit',e=>{e.preventDefault();data.assets.push({id:uid(),name:$('#assetName').value.trim(),kind:$('#assetKind').value,value:Number($('#assetValue').value)});save();modal=null;render()});
  $('#goalForm')?.addEventListener('submit',e=>{e.preventDefault();data.goals[0]={id:'g1',name:$('#goalName').value.trim()||'เป้าหมาย',target:Number($('#goalTarget').value)||0,current:Number($('#goalCurrent').value)||0};save();modal=null;render()});
  $('#autoLock')?.addEventListener('change',e=>{data.autoLock=e.target.checked;save()});
  $('#lockNow')?.addEventListener('click',()=>{unlocked=false;render()});
  $('#changePin')?.addEventListener('click',()=>{modal='pin';render()});
  $('#pinForm')?.addEventListener('submit',e=>{e.preventDefault();const a=$('#newPin1').value,b=$('#newPin2').value;if(!/^\d{4,6}$/.test(a))return alert('PIN ต้องเป็นตัวเลข 4–6 หลัก');if(a!==b)return alert('PIN ไม่ตรงกัน');data.pin=a;save();modal=null;render()});
  $('#exportBtn')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MY-FINANCE-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});
  $('#importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click());
}
document.getElementById('importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj||!Array.isArray(obj.transactions)||!Array.isArray(obj.assets))throw 0;if(confirm('Restore จะทับข้อมูลปัจจุบัน ต้องการดำเนินการหรือไม่?')){data={...defaultData,...obj};save();render()}}catch{alert('ไฟล์ Backup ไม่ถูกต้อง')}e.target.value=''})
document.addEventListener('visibilitychange',()=>{if(document.hidden){data.lastActive=Date.now();save()}else if(data.autoLock&&data.pin&&Date.now()-Number(data.lastActive||0)>60000){unlocked=false;render()}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
